### ISSUE TITLE
Heralding import error w/ Python 3.8.x

### ISSUE THREAD

**Issue by t3chn0m4g3** [johnnykv/heralding#129]
When executing heralding (from master) with python 3.8.x I get the following import error:

```
heralding    | Traceback (most recent call last):
heralding    |   File "/usr/bin/heralding", line 24, in <module>
heralding    |     import heralding.honeypot
heralding    |   File "/usr/lib/python3.8/site-packages/heralding/honeypot.py", line 33, in <module>
heralding    |     from ipify import get_ip
heralding    |   File "/usr/lib/python3.8/site-packages/ipify/__init__.py", line 31, in <module>
heralding    |     from .ipify import get_ip
heralding    |   File "/usr/lib/python3.8/site-packages/ipify/ipify.py", line 14, in <module>
heralding    |     from .settings import API_URI, MAX_TRIES, USER_AGENT
heralding    |   File "/usr/lib/python3.8/site-packages/ipify/settings.py", line 9, in <module>
heralding    |     from platform import mac_ver, win32_ver, linux_distribution, system
heralding    | ImportError: cannot import name 'linux_distribution' from 'platform' (/usr/lib/python3.8/platform.py)
```

**Comment by johnnykv** [comment]
Could you check if `pip install distro` "fixes" the issue?

**Comment by johnnykv** [comment]
Apparently  linux_distribution was removed from platform in python 3.8 and one of our dependencies (ipify) has not been updated to reflect this.

A pull request is pending: rdegges/python-ipify/pull/8.

**Comment by t3chn0m4g3** [comment]
Thanks for taking this on.

**Comment by johnnykv** [comment]
Please note that beside this issues, there seems to be a few other compatibility issues with python 3.8.

**Comment by johnnykv** [comment]
Seems like the last compability issues with 3.8 has been weeded out. Could you test on your setup before i release on pypi?

**Comment by t3chn0m4g3** [comment]
@johnnykv Confirmed working. Thank you!
