### ISSUE TITLE
Wrong SSL version

### ISSUE THREAD

**Issue by Fosocles** [johnnykv/heralding#135]
After some time, I get this error

2020-03-24 02:03:56,224 (asyncio) Task exception was never retrieved
future: <Task finished name='Task-7889' coro=<HandlerBase.handle_session() done, defined at /usr/lib/python3.8/site-packages/heralding/capabilities/handlerbase.py:74> exception=SSLError(1, '[SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1108)')>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/heralding/capabilities/handlerbase.py", line 86, in handle_session
    await asyncio.wait_for(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/usr/lib/python3.8/site-packages/heralding/capabilities/rdp.py", line 57, in execute_capability
    await self._handle_session(reader, writer, session)
  File "/usr/lib/python3.8/site-packages/heralding/capabilities/rdp.py", line 87, in _handle_session
    await tls_obj.do_tls_handshake()
  File "/usr/lib/python3.8/site-packages/heralding/libs/msrdp/tls.py", line 48, in do_tls_handshake
    self._tlsObj.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1108)

**Comment by realsdx** [comment]
Can't reproduce it. Please provide the steps to reproduce the issue.

**Comment by Fosocles** [comment]
Build docker image using TPot [Dockerfile](https://github.com/dtag-dev-sec/tpotce/blob/master/docker/heralding/Dockerfile). Started Heralding and after leaving it overnight, it gives that error.

**Comment by johnnykv** [comment]
Can you produce verbose logging for this?

**Comment by Fosocles** [comment]
I will try and come back with updates.

**Comment by Fosocles** [comment]
Here are some logs. I copied a bit before and a bit after the errors (2 distinct errors).

> 2020-04-03 12:31:53,772 (heralding.capabilities.handlerbase) Accepted ssh session on XXXX:22 from YYYY:43794. (6acb16b4-338b-441a-b537-3cf9c2b1ff48)
2020-04-03 12:31:53,772 (heralding.capabilities.handlerbase) Size of session list for ssh: 1
2020-04-03 12:31:53,773 (heralding.capabilities.ssh) SSH connection received from YYYY.
2020-04-03 12:31:53,884 (asyncssh) [conn=530] Requesting key exchange
2020-04-03 12:31:53,996 (asyncssh) [conn=530] Received key exchange request
2020-04-03 12:31:53,997 (asyncssh) [conn=530] Beginning key exchange
2020-04-03 12:31:55,038 (asyncssh) [conn=530] Completed key exchange
2020-04-03 12:31:55,270 (asyncssh) [conn=530] Beginning auth for user root
2020-04-03 12:31:55,271 (asyncssh) [conn=530] Trying password auth
2020-04-03 12:31:55,271 (heralding.misc.session) ssh authentication attempt from YYYY:43794. Auth mechanism: plaintext, session id 6acb16b4-338b-441a-b537-3cf9c2b1ff48 Credentials: {"username": "root", "password": "linux2019"}
2020-04-03 12:31:55,383 (asyncssh) [conn=530] Sending disconnect: Incomplete packet (2)
2020-04-03 12:31:55,384 (heralding.capabilities.handlerbase) Closing session. (6acb16b4-338b-441a-b537-3cf9c2b1ff48)
2020-04-03 12:31:55,385 (heralding.misc.session) Session with session id 6acb16b4-338b-441a-b537-3cf9c2b1ff48 ended
2020-04-03 12:31:55,385 (heralding.capabilities.ssh) SSH connection error: Incomplete packet
2020-04-03 12:31:58,697 (heralding.capabilities.handlerbase) Accepted rdp session on XXXX:3389 from ZZZZ:41874. (b7a306e9-bb90-4adc-863a-6304f0812c60)
2020-04-03 12:31:58,698 (heralding.capabilities.handlerbase) Size of session list for rdp: 1
2020-04-03 12:31:58,817 (heralding.capabilities.rdp) Sent x244CLinetConnectionConfirm PDU
2020-04-03 12:31:58,817 (heralding.capabilities.rdp) RDP TLS initilization
2020-04-03 12:31:59,037 (heralding.capabilities.handlerbase) Closing session. (b7a306e9-bb90-4adc-863a-6304f0812c60)
2020-04-03 12:31:59,037 (heralding.misc.session) Session with session id b7a306e9-bb90-4adc-863a-6304f0812c60 ended
2020-04-03 12:31:59,037 (asyncio) Task exception was never retrieved
future: <Task finished name='Task-4715' coro=<HandlerBase.handle_session() done, defined at /usr/lib/python3.8/site-packages/heralding/capabilities/handlerbase.py:74> exception=SSLError(1, '[SSL: SSLV3_ALERT_UNEXPECTED_MESSAGE] sslv3 alert unexpected message (_ssl.c:1108)')>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/heralding/capabilities/handlerbase.py", line 86, in handle_session
    await asyncio.wait_for(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/usr/lib/python3.8/site-packages/heralding/capabilities/rdp.py", line 57, in execute_capability
    await self._handle_session(reader, writer, session)
  File "/usr/lib/python3.8/site-packages/heralding/capabilities/rdp.py", line 87, in _handle_session
    await tls_obj.do_tls_handshake()
  File "/usr/lib/python3.8/site-packages/heralding/libs/msrdp/tls.py", line 48, in do_tls_handshake
    self._tlsObj.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_UNEXPECTED_MESSAGE] sslv3 alert unexpected message (_ssl.c:1108)
2020-04-03 12:32:02,417 (asyncssh) [conn=531] Accepted SSH connection on XXXX, port 22
2020-04-03 12:32:02,418 (asyncssh) [conn=531]   Client address: AAAA, port 46266
2020-04-03 12:32:02,418 (heralding.capabilities.handlerbase) Accepted ssh session on XXXX:22 from AAAA:46266. (2a138514-6160-429c-8c57-1ba856af300b)
2020-04-03 12:32:02,419 (heralding.capabilities.handlerbase) Size of session list for ssh: 1
2020-04-03 12:32:02,419 (heralding.capabilities.ssh) SSH connection received from AAAA.
2020-04-03 12:32:03,585 (asyncssh) [conn=531] Requesting key exchange
2020-04-03 12:32:03,905 (asyncssh) [conn=531] Received key exchange request
2020-04-03 12:32:03,906 (asyncssh) [conn=531] Beginning key exchange
2020-04-03 12:32:04,553 (asyncssh) [conn=531] Completed key exchange
2020-04-03 12:32:05,196 (asyncssh) [conn=531] Beginning auth for user root
2020-04-03 12:32:05,197 (asyncssh) [conn=531] Trying password auth
2020-04-03 12:32:05,197 (heralding.misc.session) ssh authentication attempt from AAAA:46266. Auth mechanism: plaintext, session id 2a138514-6160-429c-8c57-1ba856af300b Credentials: {"username": "root", "password": "Zxc12345"}
2020-04-03 12:32:07,639 (asyncssh) [conn=531] Sending disconnect: Incomplete packet (2)
2020-04-03 12:32:07,640 (heralding.capabilities.handlerbase) Closing session. (2a138514-6160-429c-8c57-1ba856af300b)
2020-04-03 12:32:07,640 (heralding.misc.session) Session with session id 2a138514-6160-429c-8c57-1ba856af300b ended
2020-04-03 12:32:07,641 (heralding.capabilities.ssh) SSH connection error: Incomplete packet
2020-04-03 12:32:12,906 (asyncssh) [conn=532] Accepted SSH connection on XXXX, port 22
2020-04-03 12:32:12,906 (asyncssh) [conn=532]   Client address: BBBB, port 44413
2020-04-03 12:32:12,907 (heralding.capabilities.handlerbase) Accepted ssh session on XXXX:22 from BBBB:44413. (b2beb7c3-2ca3-459e-86b1-620dc5b7afeb)
2020-04-03 12:32:12,907 (heralding.capabilities.handlerbase) Size of session list for ssh: 1
2020-04-03 12:32:12,907 (heralding.capabilities.ssh) SSH connection received from BBBB.
2020-04-03 12:32:23,474 (heralding.capabilities.handlerbase) Closing session. (b2beb7c3-2ca3-459e-86b1-620dc5b7afeb)
2020-04-03 12:32:23,474 (heralding.misc.session) Session with session id b2beb7c3-2ca3-459e-86b1-620dc5b7afeb ended
2020-04-03 12:32:23,475 (heralding.capabilities.ssh) SSH connection error: [Errno 104] Connection reset by peer
2020-04-03 12:32:24,385 (heralding.capabilities.handlerbase) Accepted rdp session on XXXX:3389 from CCCC:62082. (bff74784-72a1-453a-bc9b-2d51e2106706)
2020-04-03 12:32:24,386 (heralding.capabilities.handlerbase) Size of session list for rdp: 1
2020-04-03 12:32:24,387 (heralding.capabilities.rdp) Sent x244CLinetConnectionConfirm PDU
2020-04-03 12:32:24,387 (heralding.capabilities.rdp) RDP TLS initilization
2020-04-03 12:32:25,727 (heralding.capabilities.handlerbase) Unexpected end of session: [Errno 104] Connection reset by peer, errno: 104. (bff74784-72a1-453a-bc9b-2d51e2106706)
2020-04-03 12:32:25,727 (heralding.capabilities.handlerbase) Closing session. (bff74784-72a1-453a-bc9b-2d51e2106706)
2020-04-03 12:32:25,728 (heralding.misc.session) Session with session id bff74784-72a1-453a-bc9b-2d51e2106706 ended
2020-04-03 12:32:26,002 (asyncssh) [conn=533] Accepted SSH connection on XXXX, port 22
2020-04-03 12:32:26,003 (asyncssh) [conn=533]   Client address: DDDD, port 37964
2020-04-03 12:32:26,003 (heralding.capabilities.handlerbase) Accepted ssh session on XXXX:22 from DDDD:37964. (feda48f0-c102-4b98-a50b-4fabcd3de658)
2020-04-03 12:32:26,003 (heralding.capabilities.handlerbase) Size of session list for ssh: 1
2020-04-03 12:32:26,004 (heralding.capabilities.ssh) SSH connection received from DDDD.
2020-04-03 12:32:26,163 (asyncssh) [conn=533] Requesting key exchange
2020-04-03 12:32:26,323 (asyncssh) [conn=533] Received key exchange request
2020-04-03 12:32:26,324 (asyncssh) [conn=533] Beginning key exchange
2020-04-03 12:32:26,645 (asyncssh) [conn=533] Completed key exchange
2020-04-03 12:32:26,963 (asyncssh) [conn=533] Beginning auth for user root
2020-04-03 12:32:26,963 (asyncssh) [conn=533] Trying password auth
2020-04-03 12:32:26,964 (heralding.misc.session) ssh authentication attempt from DDDD:37964. Auth mechanism: plaintext, session id feda48f0-c102-4b98-a50b-4fabcd3de658 Credentials: {"username": "root", "password": "abccp713CP~!@"}
2020-04-03 12:32:27,124 (asyncssh) [conn=533] Sending disconnect: Incomplete packet (2)
2020-04-03 12:32:27,125 (heralding.capabilities.handlerbase) Closing session. (feda48f0-c102-4b98-a50b-4fabcd3de658)
2020-04-03 12:32:27,125 (heralding.misc.session) Session with session id feda48f0-c102-4b98-a50b-4fabcd3de658 ended
2020-04-03 12:32:27,125 (heralding.capabilities.ssh) SSH connection error: Incomplete packet
2020-04-03 12:32:35,000 (asyncssh) [conn=534] Accepted SSH connection on XXXX, port 22
2020-04-03 12:32:35,000 (asyncssh) [conn=534]   Client address: EEEE, port 60800
2020-04-03 12:32:35,001 (heralding.capabilities.handlerbase) Accepted ssh session on XXXX:22 from EEEE:60800. (03dec3d6-ebd0-439d-a436-d7c052e49258)
2020-04-03 12:32:35,001 (heralding.capabilities.handlerbase) Size of session list for ssh: 1
2020-04-03 12:32:35,002 (heralding.capabilities.ssh) SSH connection received from EEEE.
2020-04-03 12:32:35,348 (asyncssh) [conn=534] Requesting key exchange
2020-04-03 12:32:35,695 (asyncssh) [conn=534] Received key exchange request
2020-04-03 12:32:35,695 (asyncssh) [conn=534] Beginning key exchange
2020-04-03 12:32:36,393 (asyncssh) [conn=534] Completed key exchange
2020-04-03 12:32:37,085 (asyncssh) [conn=534] Beginning auth for user root
2020-04-03 12:32:37,086 (asyncssh) [conn=534] Trying password auth
2020-04-03 12:32:37,086 (heralding.misc.session) ssh authentication attempt from EEEE:60800. Auth mechanism: plaintext, session id 03dec3d6-ebd0-439d-a436-d7c052e49258 Credentials: {"username": "root", "password": "Admin@800"}
2020-04-03 12:32:37,434 (asyncssh) [conn=534] Sending disconnect: Incomplete packet (2)
2020-04-03 12:32:37,435 (heralding.capabilities.handlerbase) Closing session. (03dec3d6-ebd0-439d-a436-d7c052e49258)
2020-04-03 12:32:37,435 (heralding.misc.session) Session with session id 03dec3d6-ebd0-439d-a436-d7c052e49258 ended
2020-04-03 12:32:37,435 (heralding.capabilities.ssh) SSH connection error: Incomplete packet
2020-04-03 12:32:47,943 (asyncssh) [conn=535] Accepted SSH connection on XXXX, port 22
2020-04-03 12:32:47,943 (asyncssh) [conn=535]   Client address: FFFF, port 58368
2020-04-03 12:32:47,943 (heralding.capabilities.handlerbase) Accepted ssh session on XXXX:22 from FFFF:58368. (070f2123-9139-4cf7-b495-5b042de140cc)
2020-04-03 12:32:47,943 (heralding.capabilities.handlerbase) Size of session list for ssh: 1
2020-04-03 12:32:47,944 (heralding.capabilities.ssh) SSH connection received from FFFF.
2020-04-03 12:32:48,132 (asyncssh) [conn=535] Requesting key exchange
2020-04-03 12:32:48,471 (asyncssh) [conn=535] Received key exchange request
2020-04-03 12:32:48,471 (asyncssh) [conn=535] Beginning key exchange
2020-04-03 12:32:48,994 (heralding.capabilities.handlerbase) Accepted rdp session on XXXX:3389 from ZZZZ:49492. (b96bb2d3-77b7-419c-8dd7-75cd61101052)
2020-04-03 12:32:48,994 (heralding.capabilities.handlerbase) Size of session list for rdp: 1
2020-04-03 12:32:48,996 (heralding.capabilities.rdp) Sent x244CLinetConnectionConfirm PDU
2020-04-03 12:32:48,996 (heralding.capabilities.rdp) RDP TLS initilization
2020-04-03 12:32:49,165 (heralding.capabilities.handlerbase) Closing session. (b96bb2d3-77b7-419c-8dd7-75cd61101052)
2020-04-03 12:32:49,165 (heralding.misc.session) Session with session id b96bb2d3-77b7-419c-8dd7-75cd61101052 ended
2020-04-03 12:32:49,166 (asyncio) Task exception was never retrieved
future: <Task finished name='Task-4732' coro=<HandlerBase.handle_session() done, defined at /usr/lib/python3.8/site-packages/heralding/capabilities/handlerbase.py:74> exception=SSLError(1, '[SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1108)')>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/heralding/capabilities/handlerbase.py", line 86, in handle_session
    await asyncio.wait_for(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/usr/lib/python3.8/site-packages/heralding/capabilities/rdp.py", line 57, in execute_capability
    await self._handle_session(reader, writer, session)
  File "/usr/lib/python3.8/site-packages/heralding/capabilities/rdp.py", line 87, in _handle_session
    await tls_obj.do_tls_handshake()
  File "/usr/lib/python3.8/site-packages/heralding/libs/msrdp/tls.py", line 48, in do_tls_handshake
    self._tlsObj.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1108)
2020-04-03 12:32:49,902 (asyncssh) [conn=535] Completed key exchange
2020-04-03 12:32:50,271 (asyncssh) [conn=535] Beginning auth for user zhule
2020-04-03 12:32:50,272 (asyncssh) [conn=535] Trying password auth
2020-04-03 12:32:50,272 (heralding.misc.session) ssh authentication attempt from FFFF:58368. Auth mechanism: plaintext, session id 070f2123-9139-4cf7-b495-5b042de140cc Credentials: {"username": "zhule", "password": "zhule"}
2020-04-03 12:32:50,458 (asyncssh) [conn=535] Sending disconnect: Incomplete packet (2)
2020-04-03 12:32:50,459 (heralding.capabilities.handlerbase) Closing session. (070f2123-9139-4cf7-b495-5b042de140cc)
2020-04-03 12:32:50,459 (heralding.misc.session) Session with session id 070f2123-9139-4cf7-b495-5b042de140cc ended
2020-04-03 12:32:50,459 (heralding.capabilities.ssh) SSH connection error: Incomplete packet

@johnnykv @realsdx

**Comment by johnnykv** [comment]
Note: This can be reproduced by connecting using tls versions different from tls 1.1. Currently Heralding only support tls 1.1 - this is hardcoded here: https://github.com/johnnykv/heralding/blob/711ff0c93bc99e90ae9f7de75a92880337d5ab35/heralding/libs/msrdp/tls.py#L35

As i read the RDP specification  [1] 5.4.5.1 RDP supports TLS 1.0, 1.1 and 1.2. Hence to fix this, we need to parse the  PROTOCOL_SSL field during RDP negotiation and after that select the correct TLS version - or disconnect is the protocol is unsupported.

[1] file:///home/joe/Downloads/[MS-RDPBCGR].pdf

**Comment by johnnykv** [comment]
I was wrong, PROTOCOL_SSL only indicates if SSL should be used or not - it does not indicate which version to use...

**Comment by Fosocles** [comment]
@johnnykv Just to be sure, you did see the 2 erros, right?
SSL: SSLV3_ALERT_UNEXPECTED_MESSAGE and SSL: WRONG_SSL_VERSION.

**Comment by johnnykv** [comment]
@Fosocles No, I did not notice the UNEXPECTED_MESSAGE :-). I still think the best approach is to circumvent this by using try/catch - and raise a separate task (issue) to make the TLS handling more robust.

**Comment by Fosocles** [comment]
Ok, cool. That means modifying the code, right? I don't know if I can be of any help, but I can deploy the changes in my test and production environments and provide logs, if you want.
