### ISSUE TITLE
SSHException randomly generated

### ISSUE THREAD

**Issue by shinji257** [johnnykv/heralding#19]
For some reason the SSH module seems to be throwing random SSHExceptions.  It might of happened before... I backgrounded it after seeing the first one and seeing it working with the exception of SMTP.  For the most part it does seem to work but every now and again this shows up.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python2.7/dist-packages/heralding/capabilities/handlerbase.py", line 84, in handle_session
    self.execute_capability(address, gsocket, session)
  File "/usr/local/lib/python2.7/dist-packages/heralding/capabilities/ssh.py", line 47, in execute_capability
    SshWrapper(address, None, socket, session, self.options, self.key)
  File "/usr/local/lib/python2.7/dist-packages/heralding/capabilities/ssh.py", line 70, in __init__
    SSHHandler.__init__(self, request, client_address, server)
  File "/usr/local/lib/python2.7/dist-packages/telnetsrv/paramiko_ssh.py", line 66, in __init__
    BaseRequestHandler.__init__(self, request, client_address, server)
  File "/usr/lib/python2.7/SocketServer.py", line 650, in __init__
    self.setup()
  File "/usr/local/lib/python2.7/dist-packages/heralding/capabilities/ssh.py", line 90, in setup
    self.transport.start_server(server=self)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 559, in start_server
    raise SSHException('Negotiation failed.')
SSHException: Negotiation failed.
<Greenlet at 0x7f4e8bc76b90: _handle_and_close_when_done(<bound method SSH.handle_session of <heralding.cap, <bound method StreamServer.do_close of <StreamServ, (<socket at 0x7f4e84eed050 fileno=[Errno 9] Bad fi)> failed with SSHException
```
When it happens things move along and continue.

**Comment by johnnykv** [comment]
Yeah, that happens from time to time. There are many reasons that this happens, port scans, protocol fuzzing, etc. This is a non-critical issue, and will be fixed im the next release.
