### ISSUE TITLE
Handle invalid SSH banner

### ISSUE THREAD

**Issue by johnnykv** [johnnykv/heralding#21]
This seems to happen when connecting to the SSH capability and entering bogus data.
To reproduce do `nc localhost 22` and enter random characters.

``` syslog
Aug 19 17:19:55 heralding heralding[21523]: Traceback (most recent call last):
Aug 19 17:19:55 heralding heralding[21523]: File "/home/heralding/virtualenv/local/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
Aug 19 17:19:55 heralding heralding[21523]: result = self._run(*self.args, **self.kwargs)
Aug 19 17:19:55 heralding heralding[21523]: File "/home/heralding/virtualenv/local/lib/python2.7/site-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
Aug 19 17:19:55 heralding heralding[21523]: return handle(*args_tuple)
Aug 19 17:19:55 heralding heralding[21523]: File "/home/heralding/virtualenv/local/lib/python2.7/site-packages/heralding/capabilities/handlerbase.py", line 84, in handle_session
Aug 19 17:19:55 heralding heralding[21523]: self.execute_capability(address, gsocket, session)
Aug 19 17:19:55 heralding heralding[21523]: File "/home/heralding/virtualenv/local/lib/python2.7/site-packages/heralding/capabilities/ssh.py", line 47, in execute_capability
Aug 19 17:19:55 heralding heralding[21523]: SshWrapper(address, None, socket, session, self.options, self.key)
Aug 19 17:19:55 heralding heralding[21523]: File "/home/heralding/virtualenv/local/lib/python2.7/site-packages/heralding/capabilities/ssh.py", line 70, in __init__
Aug 19 17:19:55 heralding heralding[21523]: SSHHandler.__init__(self, request, client_address, server)
Aug 19 17:19:55 heralding heralding[21523]: File "/home/heralding/virtualenv/local/lib/python2.7/site-packages/telnetsrv/paramiko_ssh.py", line 66, in __init__
Aug 19 17:19:55 heralding heralding[21523]: BaseRequestHandler.__init__(self, request, client_address, server)
Aug 19 17:19:55 heralding heralding[21523]: File "/usr/lib/python2.7/SocketServer.py", line 653, in __init__
Aug 19 17:19:55 heralding heralding[21523]: self.setup()
Aug 19 17:19:55 heralding heralding[21523]: File "/home/heralding/virtualenv/local/lib/python2.7/site-packages/heralding/capabilities/ssh.py", line 90, in setup
Aug 19 17:19:55 heralding heralding[21523]: self.transport.start_server(server=self)
Aug 19 17:19:55 heralding heralding[21523]: File "/home/heralding/virtualenv/local/lib/python2.7/site-packages/paramiko/transport.py", line 558, in start_server
Aug 19 17:19:55 heralding heralding[21523]: raise e
Aug 19 17:19:55 heralding heralding[21523]: SSHException: Error reading SSH protocol banner
Aug 19 17:19:55 heralding heralding[21523]: <Greenlet at 0x7f815904be10: _handle_and_close_when_done(<bound method SSH.handle_session of <heralding.cap, <bound method StreamServer.do_close of <StreamServ, (<socket at 0x7f815d62ec50 fileno=[Errno 9] Bad fi)> failed with SSHException
```

**Comment by johnnykv** [comment]
@glaslos can you reproduce?

**Comment by glaslos** [comment]
Not really, redirecting all connections on port 22 to Heralding. Could be non SSH traffic, partial data, you name it... Maybe Heralding should capture the pcap for exceptions?

**Comment by Maleus** [comment]
Is the work around to just not listen on port 22?

**Comment by glaslos** [comment]
I think that's too drastic. Heralding keeps running despite the exception. You just loose some potential credentials. Could be an issue in the ssh library or just malformed requests.

**Comment by yvshri** [comment]
As @glaslos suggested, I looked into the error. [This](https://github.com/paramiko/paramiko/issues/337) and [this](https://github.com/paramiko/paramiko/issues/389) issues from paramiko's repo suggest that Paramiko doesn't support Greenlets. As far as I have understood, heralding is using greenlets. Could this be the issue?

**Comment by johnnykv** [comment]
I am not convinced that it's the root cause here (but I could be wrong!). As I see it, we are able to reproduce the issue by providing bogus data to port 22 which causes the exception (as expected). I would guess that if we run the same experiment without greenlets we would see the same issue.
