### ISSUE TITLE
SSLV3_ALERT_BAD_CERTIFICATE error when accessing the https webpage

### ISSUE THREAD

**Issue by markszabo** [johnnykv/heralding#29]
I've installed heralding, and http works fine, but if I try to access it via https, the browser displays a `SEC_ERROR_REUSED_ISSUER_AND_SERIAL` error message, while heralding throws the following exception:
```
(...)
2017-01-15 17:42:35,615 (heralding.honeypot) Started ftp capability listening on port 21
2017-01-15 17:42:35,617 (root) Privileges dropped, running as nobody/nogroup.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 173, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 702, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 270, in __init__
    raise x
SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:590)
Sun Jan 15 17:43:05 2017 <Greenlet at 0x7f0e98d83a50: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <StreamServ, (<socket at 0x7f0e91e66690 fileno=[Errno 9] Bad fi)> failed with SSLError
```
I've reinstalled it and the error seems to persist. Any idea? (I'm using Ubuntu with all updates installed.)

**Comment by johnnykv** [comment]
Uhm, yeah. I think this relates to reusing the same issuer and serial in Heraldings SSL config. I think it happens because the browser saves information regarding the sites certificate the first time it see the site, the problem comes when you delete and recreate herading - now the browser will see a new certificate with the same issuer and *serial* - and that seems spooky to the browser and hence it alerts.

Am i right in saying, that if you try a new browser this does not happen?

**Comment by markszabo** [comment]
Yes, that solved the issue, thank you
