### ISSUE TITLE
Traceback error from nmap scan

### ISSUE THREAD

**Issue by Maleus** [johnnykv/heralding#31]
The software works fine until I run an Nmap scan on the box, which results in the following error:

This is a fresh install of Debian 14.04 LTS, with this software, patches and git being the only items installed.

The nmap scan has no flags, and is just a default scan used to verify ports being open.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python2.7/dist-packages/Heralding-0.1.15-py2.7.egg/heralding/capabilities/handlerbase.py", line 84, in handle_session
    self.execute_capability(address, gsocket, session)
  File "/usr/local/lib/python2.7/dist-packages/Heralding-0.1.15-py2.7.egg/heralding/capabilities/ssh.py", line 48, in execute_capability
    SshWrapper(address, None, socket, session, self.options, self.key)
  File "/usr/local/lib/python2.7/dist-packages/Heralding-0.1.15-py2.7.egg/heralding/capabilities/ssh.py", line 72, in __init__
    SSHHandler.__init__(self, request, client_address, server)
  File "/usr/local/lib/python2.7/dist-packages/telnetsrv/paramiko_ssh.py", line 66, in __init__
    BaseRequestHandler.__init__(self, request, client_address, server)
  File "/usr/lib/python2.7/SocketServer.py", line 647, in __init__
    self.setup()
  File "/usr/local/lib/python2.7/dist-packages/Heralding-0.1.15-py2.7.egg/heralding/capabilities/ssh.py", line 93, in setup
    self.transport.start_server(server=self)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 564, in start_server
    raise e
EOFError
Wed Jan 25 09:19:25 2017 <Greenlet at 0x7f7abd9d30f0: _handle_and_close_when_done(<bound method SSH.handle_session of <heralding.cap, <bound method StreamServer.do_close of <StreamServ, (<socket at 0x7f7abd9d20d0 fileno=[Errno 9] Bad fi)> failed with EOFError

**Comment by johnnykv** [comment]
Can you please provide more logging before and after the exception?
Does Heralding crash - or just logs exception and continues to run?

**Comment by Maleus** [comment]
It does continue to run it seems, however it does consistently throw that error on an nmap scan.

**Comment by Maleus** [comment]
Here is the log from the Traceback above:

2017-01-25 09:11:47,063 (root) Using default config file: "/usr/local/lib/python2.7/dist-packages/Heralding-0.1.15-py2.7.egg/heralding/heralding.yml", if you want to customize values please copy this file to the current working directory
2017-01-25 09:11:47,071 (heralding.reporting.file_logger) File logger started, using file: heralding_activity.log
2017-01-25 09:11:47,072 (heralding.honeypot) Started ftp capability listening on port 21
2017-01-25 09:11:47,072 (heralding.honeypot) Started smtp capability listening on port 25
2017-01-25 09:11:47,072 (heralding.honeypot) Started Http capability listening on port 80
2017-01-25 09:11:47,073 (heralding.honeypot) Started Pop3 capability listening on port 110
2017-01-25 09:11:47,073 (heralding.honeypot) Started Pop3S capability listening on port 993
2017-01-25 09:11:47,074 (heralding.honeypot) Started https capability listening on port 443
2017-01-25 09:11:47,074 (heralding.honeypot) Started Telnet capability listening on port 23
2017-01-25 09:11:47,091 (heralding.honeypot) Started SSH capability listening on port 22
2017-01-25 09:11:47,092 (root) Privileges dropped, running as nobody/nogroup.
2017-01-25 09:12:15,512 (paramiko.transport) Exception: Error reading SSH protocol banner
2017-01-25 09:12:15,512 (paramiko.transport) Traceback (most recent call last):
2017-01-25 09:12:15,512 (paramiko.transport)   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1744, in run
2017-01-25 09:12:15,512 (paramiko.transport)     self._check_banner()
2017-01-25 09:12:15,512 (paramiko.transport)   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1892, in _check_banner
2017-01-25 09:12:15,512 (paramiko.transport)     raise SSHException('Error reading SSH protocol banner' + str(e))
2017-01-25 09:12:15,512 (paramiko.transport) SSHException: Error reading SSH protocol banner
2017-01-25 09:12:15,512 (paramiko.transport)
2017-01-25 09:12:15,515 (heralding.capabilities.ssh) Premature end of SSH session: Error reading SSH protocol banner (55def3f2-df1c-4ee6-b370-85b31bf9c6fb)

**Comment by Maleus** [comment]
Also confirmed that running nmap against ports other than 22 do not cause the error.

**Comment by johnnykv** [comment]
Thanks for the details, this issue is the same as #21
