### ISSUE TITLE
Fix SSLError while connecting to https with web browser. 

### ISSUE THREAD

**Issue by kajojify** [johnnykv/heralding#38]
When you try to connect to Heralding https using web browser (I checked Chromium and Firefox), SSLError occures:
```
 Traceback (most recent call last):
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/server.py", line 173, in wrap_socket_and_handle
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/_sslgte279.py", line 702, in wrap_socket
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/_sslgte279.py", line 270, in __init__
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:590)
Sun May 21 20:47:31 2017 <Greenlet at 0x7f058b1d1e10: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <StreamServ, (<socket at 0x7f058b190710 fileno=[Errno 9] Bad fi)> failed with SSLError

Traceback (most recent call last):
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/server.py", line 173, in wrap_socket_and_handle
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/_sslgte279.py", line 702, in wrap_socket
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/_sslgte279.py", line 270, in __init__
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:590)
Sun May 21 20:47:31 2017 <Greenlet at 0x7f058b1d1eb0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <StreamServ, (<socket at 0x7f058b190cd0 fileno=[Errno 9] Bad fi)> failed with SSLError

Traceback (most recent call last):
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/server.py", line 173, in wrap_socket_and_handle
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/_sslgte279.py", line 702, in wrap_socket
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/_sslgte279.py", line 270, in __init__
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:590)
Sun May 21 20:47:31 2017 <Greenlet at 0x7f058b1d1eb0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <StreamServ, (<socket at 0x7f058b190d10 fileno=[Errno 9] Bad fi)> failed with SSLError

Traceback (most recent call last):
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/server.py", line 173, in wrap_socket_and_handle
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/_sslgte279.py", line 702, in wrap_socket
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/_sslgte279.py", line 270, in __init__
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:590)
Sun May 21 20:47:32 2017 <Greenlet at 0x7f058b1d1eb0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <StreamServ, (<socket at 0x7f058b190d10 fileno=[Errno 9] Bad fi)> failed with SSLError

Traceback (most recent call last):
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/server.py", line 173, in wrap_socket_and_handle
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/_sslgte279.py", line 702, in wrap_socket
  File "/home/kajoj/.local/lib/python2.7/site-packages/gevent/_sslgte279.py", line 270, in __init__
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:590)
Sun May 21 20:47:37 2017 <Greenlet at 0x7f058b1d1eb0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <StreamServ, (<socket at 0x7f058b190d10 fileno=[Errno 9] Bad fi)> failed with SSLError
```
It seems, the problem relates to SSL generation.

**Comment by dwasss** [comment]
@kajojify I didn't have any issues using Chrome on the latest version of heralding. Maybe this is a legacy issue and can be closed?

**Comment by kajojify** [comment]
@dwasss Yes it is. Thank you for your observation!
