### ISSUE TITLE
Investigate exception related to paramiko and EOFERROR

### ISSUE THREAD

**Issue by johnnykv** [johnnykv/heralding#43]
The exception below was found on a running 0.2.0 instance. We need to investigate this.
```
Traceback (most recent call last):
  File "/home/jkv/virtualenvs/heralding3/lib/python3.5/site-packages/gevent-1.2.2-py3.5-linux-x86_64.egg/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/jkv/virtualenvs/heralding3/lib/python3.5/site-packages/gevent-1.2.2-py3.5-linux-x86_64.egg/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/home/jkv/virtualenvs/heralding3/lib/python3.5/site-packages/heralding/capabilities/handlerbase.py", line 84, in handle_session  
    self.execute_capability(address, gsocket, session)
  File "/home/jkv/virtualenvs/heralding3/lib/python3.5/site-packages/heralding/capabilities/ssh.py", line 47, in execute_capability
    SshWrapper(address, None, gsocket, session, self.options, self.key)
  File "/home/jkv/virtualenvs/heralding3/lib/python3.5/site-packages/heralding/capabilities/ssh.py", line 74, in __init__
    super().__init__(request, client_address, server)
  File "/home/jkv/virtualenvs/heralding3/lib/python3.5/site-packages/heralding/telnetsrv/paramiko_ssh.py", line 60, in __init__
    BaseRequestHandler.__init__(self, request, client_address, server)
  File "/usr/lib/python3.5/socketserver.py", line 679, in __init__
    self.setup()
  File "/home/jkv/virtualenvs/heralding3/lib/python3.5/site-packages/heralding/capabilities/ssh.py", line 97, in setup
    self.transport.start_server(server=self)
  File "/home/jkv/virtualenvs/heralding3/lib/python3.5/site-packages/paramiko-2.2.1-py3.5.egg/paramiko/transport.py", line 579, in start_server
    raise e
  File "/home/jkv/virtualenvs/heralding3/lib/python3.5/site-packages/paramiko-2.2.1-py3.5.egg/paramiko/transport.py", line 1821, in run
    ptype, m = self.packetizer.read_message()
  File "/home/jkv/virtualenvs/heralding3/lib/python3.5/site-packages/paramiko-2.2.1-py3.5.egg/paramiko/packet.py", line 423, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
  File "/home/jkv/virtualenvs/heralding3/lib/python3.5/site-packages/paramiko-2.2.1-py3.5.egg/paramiko/packet.py", line 276, in read_all
    raise EOFError()
EOFError
Fri Jun 23 19:44:24 2017 <Greenlet at 0x7f9661193178: _handle_and_close_when_done(<bound method HandlerBase.handle_session of <heral, <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with EOFError
```

**Comment by kajojify** [comment]
Once I got this exception, but don't remember how. Could you please tell, how to reproduce it?

**Comment by johnnykv** [comment]
I saw it on a deployed box. I have not tried to reproduce, but i suspect it happens if the connection is not shutdown properly... maybe try to connect and drop the connection silently.

**Comment by johnnykv** [comment]
Don't spend time on it now, it might be a wild goose chase - but down the road we need to investigate it...

**Comment by johnnykv** [comment]
More detailed exception (verbose logging enabled):
```
2017-06-28 17:18:16,727 (heralding.capabilities.handlerbase) Closing session. (c8ecd1f3-3c53-4247-9ae3-dc959b8e3be4)
2017-06-28 17:18:20,515 (heralding.capabilities.handlerbase) Accepted ssh session on port 22 from 104.X.Y.Z:51913. (3cc3050a-7e47-4b27-870a-322c8646a96f)
2017-06-28 17:18:20,516 (heralding.capabilities.handlerbase) Size of session list for ssh: 1
2017-06-28 17:18:26,675 (heralding.capabilities.handlerbase) Closing session. (3cc3050a-7e47-4b27-870a-322c8646a96f)
Traceback (most recent call last):
  File "/home/jkv/virtualenvs/heralding3/lib/python3.5/site-packages/gevent-1.2.2-py3.5-linux-x86_64.egg/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/jkv/virtualenvs/heralding3/lib/python3.5/site-packages/gevent-1.2.2-py3.5-linux-x86_64.egg/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/home/jkv/virtualenvs/heralding3/lib/python3.5/site-packages/heralding/capabilities/handlerbase.py", line 84, in handle_session
    self.execute_capability(address, gsocket, session)
  File "/home/jkv/virtualenvs/heralding3/lib/python3.5/site-packages/heralding/capabilities/ssh.py", line 47, in execute_capability
    SshWrapper(address, None, gsocket, session, self.options, self.key)
  File "/home/jkv/virtualenvs/heralding3/lib/python3.5/site-packages/heralding/capabilities/ssh.py", line 74, in __init__
    super().__init__(request, client_address, server)
  File "/home/jkv/virtualenvs/heralding3/lib/python3.5/site-packages/heralding/telnetsrv/paramiko_ssh.py", line 60, in __init__
    BaseRequestHandler.__init__(self, request, client_address, server)
  File "/usr/lib/python3.5/socketserver.py", line 679, in __init__
    self.setup()
  File "/home/jkv/virtualenvs/heralding3/lib/python3.5/site-packages/heralding/capabilities/ssh.py", line 97, in setup
    self.transport.start_server(server=self)
  File "/home/jkv/virtualenvs/heralding3/lib/python3.5/site-packages/paramiko-2.2.1-py3.5.egg/paramiko/transport.py", line 579, in start_server
    raise e
  File "/home/jkv/virtualenvs/heralding3/lib/python3.5/site-packages/paramiko-2.2.1-py3.5.egg/paramiko/transport.py", line 1821, in run
    ptype, m = self.packetizer.read_message()
  File "/home/jkv/virtualenvs/heralding3/lib/python3.5/site-packages/paramiko-2.2.1-py3.5.egg/paramiko/packet.py", line 423, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
  File "/home/jkv/virtualenvs/heralding3/lib/python3.5/site-packages/paramiko-2.2.1-py3.5.egg/paramiko/packet.py", line 276, in read_all
    raise EOFError()
EOFError
Wed Jun 28 17:18:26 2017 <Greenlet at 0x7f761c415df0: _handle_and_close_when_done(<bound method HandlerBase.handle_session of <heral, <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with EOFError

2017-06-28 17:18:28,559 (heralding.capabilities.handlerbase) Accepted ssh session on port 22 from 116.X.Y.Z:12314. (57b7d408-d4a8-4752-ba4f-c18a520f0df5)
2017-06-28 17:18:28,560 (heralding.capabilities.handlerbase) Size of session list for ssh: 1

```

**Comment by johnnykv** [comment]
closing since we don't use paramiko anymore.
