### ISSUE TITLE
Investigate error "Protocol wrong type for socket".

### ISSUE THREAD

**Issue by johnnykv** [johnnykv/heralding#49]
Using this code
```python
import socket
HOST = 'localhost'    # The remote host
PORT = 25              # The same port as used by the server

i = 0
while i < 100:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.connect((HOST, PORT))
        s.close()
        i = i + 1
```

the exception below was generated on OS X, this needs to be investigated.

```text
2017-07-28 17:57:34,011 (asyncio) Fatal write error on socket transport
protocol: <asyncio.streams.StreamReaderProtocol object at 0x10e047ef0>
transport: <_SelectorSocketTransport fd=35 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 702, in write
    n = self._sock.send(data)
OSError: [Errno 41] Protocol wrong type for socket
2017-07-28 17:57:34,056 (asyncio) Fatal write error on socket transport
protocol: <asyncio.streams.StreamReaderProtocol object at 0x10e44f9e8>
transport: <_SelectorSocketTransport fd=31 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 702, in write
    n = self._sock.send(data)
OSError: [Errno 41] Protocol wrong type for socket
```

**Comment by viditgarg1999** [comment]
Maybe it’s showing error because there is a mismatch in the protocols, like the code is written in
UDP protocol but in the selectors_event.py file (line no. 702)
n = self._sock.send(data)

we have used .send which is used in TCP protocol, instead of writing it as .send try changing it to .sendto (used in UDP protocol)

Hence the command become,
If the file is client file and the data is in encrypted form then command will become,
n = self._sock.sendto(data,((HOST,PORT)))

and if data is not in Encrypted form,
n = self._sock.sendto(data.encode(),(HOST,PORT))

Now if the file is a server file and data is in encrypted form then the command will become,
n = self._sock.sendto(data,addr)   here addr is the address of the clinet
and if the data is not in Encrypted form,
n = self._sock.sendto(data.encode(),addr)
